#!/usr/bin/env bash
#
# Fetches the reference repositories this project builds on and wires the useful
# parts into .claude/. Everything it clones lands in vendor/, which is gitignored —
# the repos stay upstream and updatable rather than being copied into our history.
#
#   npm run agents:bootstrap              # clone/update everything
#   npm run agents:bootstrap -- --agents  # only refresh the vendored subagents
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR="$ROOT/vendor"
AGENTS_OUT="$ROOT/.claude/agents/vendor"

ONLY_AGENTS=false
[[ "${1:-}" == "--agents" ]] && ONLY_AGENTS=true

REPOS=(
  "obra/superpowers|Skills library: TDD, debugging, planning, subagent-driven development"
  "msitarzewski/agency-agents|180+ role subagents across marketing, product, finance, design"
  "block/buzz|Self-hostable workspace where humans and agents share the same rooms"
  "firecrawl/firecrawl-mcp-server|MCP server for search and scraping — market research"
  "D4Vinci/Scrapling|Adaptive Python scraping for pages whose selectors move"
  "FortAwesome/Font-Awesome|Icon set — the storefront vendors eleven glyphs from here"
  "goabstract/Awesome-Design-Tools|Curated design tool reference for storefront work"
  "public-apis/public-apis|Catalogue of free APIs — check before scraping anything"
)

clone_or_update() {
  local repo="$1" name dest
  name="$(basename "$repo")"
  dest="$VENDOR/$name"

  if [[ -d "$dest/.git" ]]; then
    echo "  updating $repo"
    git -C "$dest" fetch --depth 1 origin >/dev/null 2>&1 || true
    git -C "$dest" reset --hard origin/HEAD >/dev/null 2>&1 \
      || git -C "$dest" pull --ff-only >/dev/null 2>&1 || true
  else
    echo "  cloning  $repo"
    git clone --depth 1 --quiet "https://github.com/$repo.git" "$dest"
  fi
}

# Role agents worth having on hand for a one-person digital product business.
# Everything else in agency-agents stays in vendor/ and can be copied in later.
CURATED=(
  "marketing/marketing-seo-specialist.md"
  "marketing/marketing-content-creator.md"
  "marketing/marketing-growth-hacker.md"
  "marketing/marketing-email-strategist.md"
  "marketing/marketing-reddit-community-builder.md"
  "marketing/marketing-aeo-foundations.md"
  "product/product-trend-researcher.md"
  "product/product-feedback-synthesizer.md"
  "finance/finance-bookkeeper-controller.md"
  "design/design-ui-designer.md"
)

install_agents() {
  local src="$VENDOR/agency-agents"
  [[ -d "$src" ]] || { echo "  agency-agents not cloned yet — run without --agents first"; return; }

  mkdir -p "$AGENTS_OUT"
  local installed=0

  for rel in "${CURATED[@]}"; do
    [[ -f "$src/$rel" ]] || { echo "  ! missing upstream: $rel"; continue; }
    python3 "$ROOT/scripts/lib/normalise-agent.py" "$src/$rel" "$AGENTS_OUT/$(basename "$rel")"
    installed=$((installed + 1))
  done

  cat > "$AGENTS_OUT/README.md" <<'EOF'
# Vendored subagents

Generated by `npm run agents:bootstrap` from
[msitarzewski/agency-agents](https://github.com/msitarzewski/agency-agents) (MIT).

Do not edit these by hand — the bootstrap overwrites them. To change one, copy it up
into `.claude/agents/` under a new name and edit it there; the project's own agents
in that directory always take precedence.

The upstream frontmatter uses a title-cased `name`; the bootstrap rewrites it to the
kebab-case identifier Claude Code expects and records the original as `displayName`.
EOF

  echo "  installed $installed agent(s) into .claude/agents/vendor/"
}

echo "Bootstrapping agent tooling into vendor/"
mkdir -p "$VENDOR"

if [[ "$ONLY_AGENTS" == false ]]; then
  for entry in "${REPOS[@]}"; do
    clone_or_update "${entry%%|*}"
  done
fi

install_agents

cat <<'EOF'

Done. Next steps, none of them automatic:

  Superpowers skills (TDD, planning, subagent-driven development):
    /plugin marketplace add obra/superpowers
    /plugin install superpowers@superpowers-dev

  Firecrawl MCP (market research) — set FIRECRAWL_API_KEY in .env.local.
    Get a key at https://firecrawl.dev. .mcp.json already points at it.

  Scrapling (adaptive scraping):
    pip install "scrapling[fetchers]" && scrapling install

  Everything in vendor/ is gitignored. Re-run this script to update.
EOF
